[path]
# 锁屏壁纸保存驱动
drive = 'D:/'
# 锁屏壁纸保存路径
dst = 'Pictures/wallpaper/bing'
# 锁屏壁纸文件目录
src = 'AppData/Local/Packages/Microsoft.Windows.ContentDeliveryManager_cw5n1h2txyewy/LocalState/Assets'

[misc.queue]
maxlen = 20
